
#ifndef _MEDIACASTSEGMENTER_H_
#define _MEDIACASTSEGMENTER_H_

#define MEDIACASTSEGMENTER_MAJOR_VERSION      1
#define MEDIACASTSEGMENTER_MINOR_VERSION      0
#define MEDIACASTSEGMENTER_RELEASE_NUMBER      3

#ifndef MEDIACASTSEGMENTER_ABI_VERSION
#define MEDIACASTSEGMENTER_ABI_VERSION ( MEDIACASTSEGMENTER_MAJOR_VERSION * 100000 + MEDIACASTSEGMENTER_MINOR_VERSION * 1000 + MEDIACASTSEGMENTER_RELEASE_NUMBER)
#endif

#endif
