
#ifndef _SEGMENTER_H_
#define _SEGMENTER_H_

#define SEGMENTER_MAJOR_VERSION      1
#define SEGMENTER_MINOR_VERSION      0
#define SEGMENTER_RELEASE_NUMBER      2

#ifndef SEGMENTER_ABI_VERSION
#define SEGMENTER_ABI_VERSION ( SEGMENTER_MAJOR_VERSION * 100000 + SEGMENTER_MINOR_VERSION * 1000 + SEGMENTER_RELEASE_NUMBER)
#endif

#endif
